# Generated by Django 4.0.5 on 2022-07-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('Publication_date', models.DateField()),
                ('Subject_area', models.CharField(max_length=100)),
            ],
        ),
    ]
