# Generated by Django 4.0.5 on 2022-07-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('publication_date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('unavailable', 'Unavailable')], max_length=30)),
                ('subject_area', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'books',
            },
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
