# Generated by Django 4.0.5 on 2022-07-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_borrower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_to_pay', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], max_length=200, null=True)),
                ('description', models.CharField(max_length=200)),
                ('payment_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
