# Generated by Django 4.0.5 on 2022-07-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='cover',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='name',
            field=models.CharField(default='nada', max_length=200),
            preserve_default=False,
        ),
    ]
