# Generated by Django 4.0.5 on 2022-07-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_borrower_cover_alter_borrower_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='cover',
            field=models.ImageField(blank=True, default='nada', upload_to='images'),
            preserve_default=False,
        ),
    ]
